spring.application.name=shipment-service
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=shipment-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Postgres Database
spring.datasource.url=jdbc:postgresql://localhost:5433/shipmentdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=shipment
spring.datasource.password=shipment

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka topics
app.kafka.topics.order-events=order-events
app.kafka.topics.shipment-events=shipment-events
